# Build worker image (VM template)
image: Visual Studio 2017

#environment:
#  access_token:
#    secure: abc

# Build Pipeline Step > Init:
init:
  - ps: $date = Get-Date -UFormat "%d_%m_%Y_%H%M"
  - ps: echo $date
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"

# Build Pipeline Step > Install additional software:
install:  
  - curl -V
  - iscc.exe

# Build Pipeline Step > Build:
build_script:
  # Fetch Components
  - build-tools\php\php.exe build-tools\get-latest-versions\grab.php
  # Build Installer
  - iscc.exe -o build installer\Reaper-Toolbox.iss
