# Build worker image (VM template)
image: Visual Studio 2017

#environment:
#  access_token:
#    secure: abc

# Build Pipeline Step > Init:
init:
  - ps: $date = Get-Date -UFormat "%d_%m_%Y_%H%M"
  - ps: echo $date
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
  #- set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"

# Build Pipeline Step > Install additional software:
#install:  
  
# Build Pipeline Step > Build:
build_script:
  # Fetch Components, Generate "downloads\versions.txt", Generate "installer\install.iss"
  - build-tools\php\php.exe build-tools\build.php
  # List Downloads
  - ls -lhs downloads
  # Build Installer
  - echo %APPVEYOR_BUILD_VERSION%
  - echo %RELEASE_DESCRIPTION%
  - build-tools\InnoSetup6\iscc.exe /DAPP_VERSION=%APPVEYOR_BUILD_VERSION% installer\Reaper-Toolbox.iss
  # List Release Folder
  - ls -lhs release

# Define Deployment Artifacts
artifacts:
  - path: '/release/*.exe'
    name: Installer-Executable

# Deployment (Appveyor to Github Releases)
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: 'Reaper-Toolbox v$(APPVEYOR_REPO_TAG_NAME)'
  description: 'Reaper-Toolbox v$(APPVEYOR_REPO_TAG_NAME) \n [View CHANGELOG.md](https://github.com/jakoch/reaper-toolbox/blob/master/CHANGELOG.md)'
  artifact: Installer-Executable
  draft: false
  prerelease: false
  on:
    branch: master              # release from master branch only
    APPVEYOR_REPO_TAG: true     # deploy on tag push only 
  auth_token:
    secure: J8ppEUaj+/rG+CIAz9xf996MHAJd+etyniwSPbdINFT4aBSpULhUtBsUr14DxUwq
