name: "Cleanup Releases"

on:
  # You can manually run this workflow.
  workflow_dispatch:

jobs:

# ---------------------------------------------------------------------------------------

  release-cleanup:

# ---------------------------------------------------------------------------------------

    name: "Releases Cleanup"
    runs-on: ubuntu-latest

    steps:
      - name: 🤘 Checkout Code
        uses: actions/checkout@v5 # https://github.com/actions/checkout

      - name: ✂ Releases-Cleanup
        uses: alfameCom/delete-releases@v1 # https://github.com/alfameCom/delete-releases        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with: 
          types: 'draft,prerelease,release'
          keep: '3'          
